[features]
seeds = false
skip-lint = false

[programs.localnet]
phoenix_vaults = "VLt8tiD4iUGVuxFRr1NiN63BYJGKua5rNpEcsEGzdBq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/cosmic_lab_inc.json"

[[test.genesis]]
address = "PhoeNiXZ8ByJGLkxNfZRnkUfjvmuYqLR89jjFHGqdXY"
program = "./deps/phoenix.so"

[[test.genesis]]
address = "PSMxQbAoDWDbvd9ezQJgARyq6R9L5kJAasaLDVcZwf1"
program = "./deps/phoenix_seat_manager.so"

[scripts]
test = "yarn anchor-tests"